imports:
    - { resource: parameters.yml }
swiftmailer:
    transport:  '%mailer_transport%'
    encryption: '%mailer_encryption%'
    host:       '%mailer_host%'
    port:       '%mailer_port%'
    username:   '%mailer_user%'
    password:   '%mailer_password%'

framework:
    secret: S0ME_SECRET
    templating:
        engines: ['twig']
    profiler: { only_exceptions: false }
    form: ~

doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8


    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        