<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHytyuzv\gruDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHytyuzv/gruDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHytyuzv.legacy');

    return;
}

if (!\class_exists(gruDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHytyuzv\gruDevDebugProjectContainer::class, gruDevDebugProjectContainer::class, false);
}

return new \ContainerHytyuzv\gruDevDebugProjectContainer(array(
    'container.build_hash' => 'Hytyuzv',
    'container.build_id' => '24adab20',
    'container.build_time' => 1516802224,
));
