<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD8l4qrf\gruDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD8l4qrf/gruDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerD8l4qrf.legacy');

    return;
}

if (!\class_exists(gruDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerD8l4qrf\gruDevDebugProjectContainer::class, gruDevDebugProjectContainer::class, false);
}

return new \ContainerD8l4qrf\gruDevDebugProjectContainer(array(
    'container.build_hash' => 'D8l4qrf',
    'container.build_id' => '3f82cc8a',
    'container.build_time' => 1520862079,
));
