<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQDWO3YS\gruDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQDWO3YS/gruDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQDWO3YS.legacy');

    return;
}

if (!\class_exists(gruDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQDWO3YS\gruDevDebugProjectContainer::class, gruDevDebugProjectContainer::class, false);
}

return new \ContainerQDWO3YS\gruDevDebugProjectContainer(array(
    'container.build_hash' => 'QDWO3YS',
    'container.build_id' => '7b25c8f2',
    'container.build_time' => 1516045675,
));
