<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5vz9rzw\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5vz9rzw/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container5vz9rzw.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container5vz9rzw\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container5vz9rzw\appDevDebugProjectContainer(array(
    'container.build_hash' => '5vz9rzw',
    'container.build_id' => 'a0f478dd',
    'container.build_time' => 1519735194,
));
