<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQNwwY0A\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQNwwY0A/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQNwwY0A.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQNwwY0A\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerQNwwY0A\appDevDebugProjectContainer(array(
    'container.build_hash' => 'QNwwY0A',
    'container.build_id' => 'fda1161e',
    'container.build_time' => 1515943977,
));
